### ISSUE TITLE
No seperate vendors bundle or code splitting

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#105]
Currently all the javascript/reactapp code is being bundled into a single file `react-checkout.js` and loaded in using Magento's static content file url, in addition most setups will have Magento [Static content signing](https://devdocs.magento.com/guides/v2.4/config-guide/cache/static-content-signing.html) enabled.

This means the javascript code bundle is only cached by the browser for as long as there is no `setup:static-content:deploy`. For the whole store. Change some static content in another module? Cache bust, your users have to redownload.

An option most frontends using webpack benefit from is to add a `[contenthash]` tag to the output file names, which enables the browser to cache these files for as long as the contents dont change. Using Magento's deployment versioning more or less makes this impossible.

In addition much of the `reactapp` code is in third party libraries, which often change less often than the application specific source code. Webpack offers features like Code Splitting and the SplitChunksPlugin to help create additional output files like a `vendors-bundle.js`.

Then if we are able to benefit from both the `[contenthash]` without deployment versioning as well as create a `vendors-[contenthash].js` file, we can benefit from much longer and more effective browser caching. Changes would be applied in another module? No problem still cached. Changes applied in `reactapp` source code? Only the quite small in comparison main bundle needs to be redownloaded, vendors is still in cache.

**Comment by wigman** [comment]
Have you done any magento implementations already where you serve a static file outside of pub/static?

I can personally really live with how it's implemented right now. We've discussed chunking and disabled it entirely, because you end up downloading only the code that you need for the checkout anyway, I don't think you're downloading _more_ than needed with the bundle, and the total checkout size is really of reasonably size (imho).

That leaves the cache-busting argument, which is more a magento-platform problem then specifically for this checkout. Which is why I'm curious to hear if you've implemented this before on other projects. I haven't seen it done before.

(in the end, the static deployment version is only a variable that changes for browser-cache-busting, so that the url is unique, nginx just rewrites any value for the static-version to pub/static)

**Comment by progammer-rkt** [comment]
@peterschriever  I am closing this issue as I see no further inputs on the topic. Feel free to reopen it if you have some brilliant idea to tackle the situation
