### ISSUE TITLE
env file configuration

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#106]
The `env.example` file now lists a couple more keys in addition to the `REACT_APP_BASE_URL`:

- REACT_APP_STORE_CODE
- REACT_APP_LANGUAGE
- REACT_APP_CURRENCY_CODE
- REACT_APP_CURRENCY_SYMBOL

What are these for? And how are websites with multiple stores/languages/currencies to be supported?

**Comment by progammer-rkt** [comment]
1. `REACT_APP_BASE_URL`: Defines the base URL for the Magento backend from which the react app needs to fetch the data. There is also a setting `proxy` available in `package.json` file which also serves the same purpose where it won't throw any CORS errors in the browser. Comes in handy in that situaion.
2. `REACT_APP_STORE_CODE`: Specifies the store code from which data needs to be collected. This data is passed in the header in all graphql queries so that store specific data will be obtained in the checkout.
3. `REACT_APP_LANGUAGE`: Specifies the locale of the react app. Based on these values translation will be applied in the react app. eg: `en_US` for English store; `de_DE` for German store etc.
4. `REACT_APP_CURRENCY_CODE`: The currency code should be used in the react app. This will be used in the `Intl.NumberFormat` to correctly format the price according to the language. eg: `EUR` for Euro, `INR` for Indian Rupee, etc.
5. `REACT_APP_CURRENCY_SYMBOL`: The currency symbol should be used in the react app. This will be used in the `Intl.NumberFormat` to correctly format the price according to the language. eg: `$` for Dollar, `¢` for Euro, etc.
6. `REACT_APP_DEFAULT_COUNTRY`: Default country the react app needs to be used. If none specified, then default to `US`.

You should place your `.env` file at the root of the react application. If there is an environment variable present, the value will be used in the entire app. The next preference will be to go for the data attribute `data-checkout_Config` where you can specify all these settings if you want. At last, it will use the default values in the app. Most of them you can find in the `src/config.js` file.

The doc lacks with this information at the moment. It will be updated with these details soon.

**Comment by progammer-rkt** [comment]
This is now added in the docs: https://hyva-themes.github.io/magento2-hyva-checkout/env_variables/
