### ISSUE TITLE
No clear way to tell when data is fetching or updating | loading states

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#108]
Currently there is no clear way to tell when data is being fetched or when a mutation is processing, this makes it difficult to realize a pleasant user experience.

There are many ways in which to implement this, however id like to see a generic approach from within the core checkout code so as to standardize loading states for every backend call.

I know a `pageLoader` and `setPageLoader` function exists inside the `AppContext` however this implementation is very lackluster and it is a bad idea to set the whole page into a loading state for what may only be a small part.

**Comment by wigman** [comment]
The reason we set the whole page to be loading (with a transparent overlay) is that you need to implement a lot of dependencies otherwise.

You can't tell on forehand what data will change if you update your country, unless you define this (explicitly). In most cases, this means shipping methods + payment methods + order totals will update.

Having a global overlay means you can interact with any other component while an update is running. Otherwise, you would need to "lock" all ui-elements explicitly to prevent them from being clicked while an update is pending.

You wouldn't want someone to select another shipping method and then click "place order" while the shipping method didn't update yet, and for example order totals are still recalculated. You're legally obliged to show the right price before the buy button is clicked.
