### ISSUE TITLE
GraphQL calls such as the countries and states lists should be cached

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#116]
In my opinion much data fetching such as the lists of countries and state/region data could be cached locally. This could also help in preventing multiple calls going out for the full list of countries/regions data.

I understand we always want to fetch a fresh Quote/Cart object, however this does not count the same for data like countries / regions. Rarely if ever does this data change during the checkout process. Why dont we add some form of caching for these?

**Comment by progammer-rkt** [comment]
@peterschriever we do cache country/states requests. So the country list fetches request will happen only once and state fetch request will happen per-country basis.

An example, we are fetching states of the country initially provided that the default country is Germany. We are now switching the country from Germany -> France and now states of France will be collected. Now, if you again switch to Germany, the states won't be fetched since we already fetched German states previously.

However, if the checkout page is reloaded, these processes will happen again. we are not keeping those states/countries in the local storage. Are you saying we need to keep this in local storage?

There will be a plan to merge multiple requests sending initially to a single request too.

**Comment by progammer-rkt** [comment]
@peterschriever No inputs on this and hence, closing this issue
