### ISSUE TITLE
The translations implementation (i18n folder) is lackluster

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#118]
The translations / internationalisation implementation is extremely basic and doesnt support many of the modern features found in nearly any third party i18n library. Why is it that we implemented our own translation functionality when so many proper third party libraries exist?

Personally i find https://react.i18next.com/ to be looking quite promising.

**Comment by progammer-rkt** [comment]
@peterschriever We are currently using native solutions rather than third-party solutions in the react app. This is a decision we have taken a long way back to reduce the js bundle size least as possible.

I hope the current implementation possesses a similar approach we have in core Magento regarding the translation and it covers the translation problem on the checkout page. TBH, if there is a solution we can re-use the translation facility in Magento, then I would prefer that over the current basic implementation. Personally, I don't want to switch to any library for the translation for hyvä checkout. Still, I am open for an open talk on this. 

This is something we can consider for a future release for sure. But, there is already a solution we have used with hyvä checkout where it is possible to use the default translations in Magento itself. I want to discuss this with @wigman and can take a decision accordingly.

**Comment by jesse-deboer** [comment]
I agree on the bundle size, but I do think something like https://react.i18next.com/ would be more beneficial to the developer and also to the end user.

The bundle increase won't be huge and also the features not enough to work with. For example the capitalization of the words in the file and in the translated file need to be the same and there is no way to add plurals. These features are necessary in big projects and make at least the developer experience a lot better. 

Comparing size against developer experience/features I think implementing something like `i18next` would be beneficial, let me know what you think @progammer-rkt. 

Also, I haven't seen the Magento translation solution yet, so that might even be the better option.

**Comment by progammer-rkt** [comment]
@peterschriever @jesse-deboer since a lot of complaints raise around the current implementation of the translations, I just propose a solution which is using the Magento translation facility in the react app.

In theory, we are using a template file (translation.phtml`) to convert all the translatable strings and then pass it via a global variable `CHECKOUT_TRANSLATIONS`. Now, from the frontend we will access this data and show the translations.

Let me know your thought on this solution. The PR is: #148

**Comment by progammer-rkt** [comment]
@peterschriever @jesse-deboer the template translation is now available and we removed the json approach from the app. Hence, closing this issue
