### ISSUE TITLE
Duplicate tailwind config is confusing

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#147]
Today I was trying to adjust the tailwind config from a recent version of the `develop` checkout. I was editing `Hyva/Checkout/reactapp/src/tailwind.config.js` which wasnt changing the behaviour in `npm start` localhost webserver.. Then I noticed there is another tailwind config at `Hyva/Checkout/view/frontend/web/css/tailwind/tailwind.config.js` which does seem to work and take my changes.

Can you please clarify which tailwind config does what and why there are two in the checkout?

**Comment by progammer-rkt** [comment]
The `tailwind.config.js` comes inside `src/reactapp` is not really be using in the app. As you mentioned the configuration file which works here is `Hyva/Checkout/view/frontend/web/css/tailwind/tailwind.config.js`. The purpose of adding that file there is because the vscode needs that file in the root path of the react app in order to suggest the tailwindcss styles. 

I could not find an easy solution that will make work eslint settings, prettier settings and tailwind css together with vscode editor.

**Comment by progammer-rkt** [comment]
@peterschriever Warning message is added in the file and hence, closing this issue.
