### ISSUE TITLE
Update Magento Customer Session When User Login From Checkout

### ISSUE THREAD

**Issue by progammer-rkt** [hyva-themes/magento2-hyva-checkout#22]
Hyva checkout uses graphql to authenticate and then collect customer information within the checkout. Once the customer is logged-in, then it will append the customer token in the header for each subsequent request coming from the checkout page.

But once you go back to the cart page or any other page in the site, the customer is not signed-in mode since there is no real session exists for the customer. This issue needs to be resolved.

**Comment by jladmore** [comment]
I created a new controller request /hyva/customer/loginPost and combined the token creation and session creation in the same login post request. Its early days, but on success I return the token, success=true and errors return a message, success=false. To be honest I can't think of anyone other way of doing this and maintaining successful login state across the theme and react checkout. Thoughts?

**Comment by jladmore** [comment]
So i have done a bit of testing on this and its working fine. I might move my code over to a new GraphQL call instead of a standard controller. Not sure what your thoughts on this are. 

By creating a PHP session as well as creating a token you don't need to merge the carts anymore either, the server creates a new cart with all the required items. so you just need to grab the new cartId.. I will wait for your thoughts on the GraphQL vs controller and keep testing at my end.

**Comment by progammer-rkt** [comment]
This issue is resolved. We are now using the built-in controller `customer/ajax/login` to tackle this scenario. It authenticates the user, sets a customer session, and merges the carts. All in one solution.

Please see the related pull request: https://github.com/hyva-themes/magento2-hyva-checkout/pull/43
