### ISSUE TITLE
All Shipping and Billing Addr API calls reference the cartId from config.js

### ISSUE THREAD

**Issue by jladmore** [hyva-themes/magento2-hyva-checkout#26]
It looks like this is only read at the launch of the react checkout. So if you then change the cartId by logging in during checkout, the wrong cartId is referenced even though the local storage is updated and the new cartId is in state. 

It maybe better to pass the cartId to these API calls? I have done some tests and this seems to work ok

**Comment by progammer-rkt** [comment]
Hi @jladmore , all the API services now referring to the local storage entry directly rather than relying on the `config` data which will be populated only once in the initial time. This way all the API calls will be referring to the latest cart id and customer token stored in the local storage.

The pull request that resolves this issue is #30 and it is now available in the `develop` branch.

Please pull out the develop branch and check whether this works for you and let us know. We will be keeping this issue open for some time if in case you can check and confirm the solution works. After that, we can safely close this issue 👍
