### ISSUE TITLE
Broken Layout on Install

### ISSUE THREAD

**Issue by deedy-tech** [hyva-themes/magento2-hyva-checkout#28]
When I install the checkout and re-enable the line

<css src="Hyva_Checkout::css/styles.css" defer="defer"/>

on my Magento 2.4.1 I get the following in the checkout
![hyva_checkout](https://user-images.githubusercontent.com/52239145/115145828-82a86f00-a04b-11eb-8968-8c74e8a14ed3.jpeg)

**Comment by progammer-rkt** [comment]
Hi @deedy-tech , thanks for reporting the issue. Which branch you are using? `main` or `develop` ?

**Comment by deedy-tech** [comment]
Hi, it was the main branch

**Comment by progammer-rkt** [comment]
@deedy-tech The issue of having a broken layout is now fixed and available in the `develop` branch. `develop` branch is a new revamp of this module and you should actually use the `develop` branch instead of the `main` branch to get all the features this module offer. `develop` will be soon be merged into `main` branch. 

You can find the relevant changes in pull request #30 

Hence closing this issue.
