### ISSUE TITLE
How can we theme the application to our needs?

### ISSUE THREAD

**Issue by ericmorand** [hyva-themes/magento2-hyva-checkout#4]
Brwosing the sources, I've noticed that you are not giving your components an indentifiable and targetable class. They only come with classes that _describe the desired presentation of the content_ - which is by the way against the recommandations of the WHATWG group (https://html.spec.whatwg.org/multipage/dom.html#classes) because it puts the presentation layer into the content layer.

For example:

```jsx
        <div
            className={'relative bg-white pb-6 p-4 md:p-0 md:pr-4 text-center'}
        >
```

This is the entry point of `src/components/Elements/CartItems.jsx` and as you can see there is not way to target it to give it a custom styling.

Can you give us the recommended strategy to style your components?

Thanks by advance.

**Comment by wigman** [comment]
Hello Eric,

It's understandable that you have these questions! There's no documentation yet, and it's a work in progress. Let me quickly elaborate:

1. The Checkout is meant to become a 'Checkout Toolkit'. I imagine users writing their own presentational components, while using _the brain_ of the application: hooks and context
- all form states are in a Formik context
- all quote states are in a cart context
- all app states are in a app context
- actions and reducers hook into these contexts, enabling you to access these states and triggering actions from *anywhere*
- this means you can freely place components anywhere in your application and utilize one of these three contexts

2. The components you currently see belong to the checkout at hyva.io, where we use TailwindCss, which is utility-based
I will include a Tailwind config soon, that enables you to generate a css file for these components.
If you want to try it out right now, just for a quick demo on your local system, please pull in the css file from hyva.io
You could already get going with a basic tailwind css config and compile you're own, it's very easy to get started with.

3. There will be multiple layouts, with 'pagination' logic, so that you can easily create an 'one page checkout', or a 2, 3, 4 step!

4. We'll create a layout that is fully 'themed' later on.

5. We still need to do a lot of refactoring, pulling all the actions out of the contexts for example. We'd advise to take the current state and build it out to your needs, or wait until we've finished it further. Don't rely on having an upgrade path where you can pull in a new version of this repository and have a working update, at this point I don't think that will be possible :)
We've already built 2 checkouts with this code-base, and those are basically finished and are no longer 'in sync' with this repo.

Lastly, if it helps you getting started with it right now, I have no objections to a PR that adds explanatory classes to the components.
I use the React Extension in my browser where I can fully inspect all elements and states which means I don't need the classes to inspect elements in the source-code.

**Comment by progammer-rkt** [comment]
I agree with your point @ericmorand. but this can be considered as a limitation of tailwindcss. But, this is no longer a concern though. Because a react component clearly explains what it is and what it is doing. So when we use the react developer tools, it will give us a clear picture of what is what and which is which.

When I was starting with tailwindcss, the very question you asked popup into my mind. Once I familiarised with it and used in a couple of react project, this is no longer a concern for me. Because in react, the components are the building blocks and css is one of the constituting blocks of a component. As long as we keep the components small and compact, this won't be a real blocker for you.

There is a major revamp work done on this in the `develop` branch and soon will be merged into the `main` branch. You can explore

Closing this issue as we are going to use tailwindcss in this module and there is no intention to going back to any other css technology. Feel free to open this if you have some kind of idea to give meaning to each HTML element on the scope of tailwindcss.
