### ISSUE TITLE
Extension points for payment method integration

### ISSUE THREAD

**Issue by schmengler** [hyva-themes/magento2-hyva-checkout#41]
Server side: payment configuration provider

Client side: create directory where payment components can be dropped in and (ideally) picked up by webpack

@progammer-rkt please fill in details when further discussed

**Comment by schmengler** [comment]
Partially covered by #40 :+1:

**Comment by progammer-rkt** [comment]
We have a proof of concept on this. In a nutshell, this is what we need to in order to integrate a payment method into Hyvä Checkout react side.

```
"config": {
    "paymentMethodsRepo": {
      "payone": "git@github.com:hyva-themes/magento2-hyva-checkout-payone.git"
    }
  },
```
With this configuration in place and you perform `npm install`, then you are good to go.

Soon the doc will be updated with a detailed explanation of this feature. Stay tuned.
