### ISSUE TITLE
Preselect default country

### ISSUE THREAD

**Issue by schmengler** [hyva-themes/magento2-hyva-checkout#58]
The countries GraphQl API needs to be changed to include a `default` field for this

**Comment by progammer-rkt** [comment]
When I checked this in default luma checkout, this value is passed via `window.checkoutConfig.defaultCountryId`. Since we are already passing this information in Hyvä Checkout via data attributes, I thought it will be straight forward to use that implementation to pass this information.

But in the future, we will be come up with a solution to collect the `checkoutConfig` info via a GQL endpoint.

**Comment by progammer-rkt** [comment]
This is included in the pull request: #83
