### ISSUE TITLE
incorrect conditional className generation

### ISSUE THREAD

**Issue by DanielRuf** [hyva-themes/magento2-hyva-checkout#78]
It seems the conditional class rendering is not correct as there are instances of `false`:

Current code:
![grafik](https://user-images.githubusercontent.com/827205/122898231-0122d500-d34b-11eb-91b4-cb28b48e7d52.png)

![grafik](https://user-images.githubusercontent.com/827205/122898876-8c03cf80-d34b-11eb-876b-5c62f0f849e1.png)

Fixed code:
![grafik](https://user-images.githubusercontent.com/827205/122898172-f5371300-d34a-11eb-9a55-dac36125b43a.png)

![grafik](https://user-images.githubusercontent.com/827205/122898095-e6e8f700-d34a-11eb-88e1-117cf6b34674.png)

See also:
https://reactjs.org/docs/faq-styling.html
https://www.pluralsight.com/guides/applying-classes-conditionally-react
https://stackoverflow.com/a/39281166/753676

**Comment by DanielRuf** [comment]
PS: the button seems to need some more work (at least the line break and the button size do not match):

![grafik](https://user-images.githubusercontent.com/827205/122899198-e69d2b80-d34b-11eb-82c6-cdb819ad409d.png)

**Comment by progammer-rkt** [comment]
Hi @DanielRuf, thanks for reporting the issue.

Yes, in some places in the `className` section, we are using an AND logic expression rather than recommending a ternary operator. When we use AND expression, there is the possibility of coming `false` in the class list. I choose AND operation in some places because of the following reasons.

- this does not produce any kind of performance issue.
- It has the advantage of making the `className` part short. 
- I personally don't like ternary operators and I normally try to avoid their usage.  Because I am lazy.

It brings the following drawbacks for sure
- It inserts `false` or `undefined` words in the class list sometimes. but, this feels noisy only when we inspect the classes via browser
- Tailwindcss using ternary operators in their examples in the cases we need to include some classes dynamically.

I think this improvement is good to have and looking forward to pull request for such improvements. There is no time to deal with these improvements at the moment.

**Comment by wigman** [comment]
I'm removing these wherever I encounter them. PRs are always welcome if anyone wants to change them at once.
